### ISSUE TITLE
As a pepper user, I want today.noi.bz.it to work on the pepper tablet

### ISSUE THREAD

**Issue by ohnewein** [idm-suedtirol/NOI-display#11]
- [x] find a way to debug on this browser
- [x] adapt javascript if possible

Pepper is a robot the UNIBZ and NOI will use in the NOI foyer to deliver information to guests.

Pepper has a tablet mounted on his chest. On this tablet he can display further sources of information and one important source will be today.noi.bz.it to inform guests about events happening at NOI.

The tablet runs a basic Android version and today.noi.bz.it does not work correctly on it. See screenshot created using the following emulator:

https://www.apkonline.net/runapk/create-androidapk.html?app=android_6.0_blank

![Screenshot from 2019-05-24 17-42-52](https://user-images.githubusercontent.com/414797/58340262-ac4ec080-7e4b-11e9-8e7e-ca31f66e3bb0.png)

Can we modify the JS to have it working on this basic browser as well?

**Comment by bertolla** [comment]
It's quiet hard to find information about this browser. Is there no way to install firefox or chrome on this tablet?

**Comment by ohnewein** [comment]
No, they told me it is not possible to upgrade the software on the tablet.

**Comment by bertolla** [comment]
@ohnewein Could you please ask Andrea if he could check with http://test.today.noi.bz.it.s3-website-eu-west-1.amazonaws.com/ and if it displays in a strange way I need the resolution of his device and need to know if he intends to put the browser full-screen.
For the rest it should work now

**Comment by ohnewein** [comment]
@ajanes can you provide feedback to @bertolla ?

**Comment by ajanes** [comment]
Hi,

Sorry, it does not work and I don't know how to provide you with a testing environment. Maybe we fix this when the robot is in the NOI techpark?
![IMG_1057](https://user-images.githubusercontent.com/10242827/59098248-0fe2ee80-8920-11e9-9bd0-ba7eb7903602.jpg)

Bye,
Andrea

**Comment by bertolla** [comment]
Ok but it seems to be just the css stuff which has problems, which means that for the rest it works

**Comment by ajanes** [comment]
Yes, now it loads the events, which before I think it did not. So formatting is the only thing left...

**Comment by bertolla** [comment]
http://test.today.noi.bz.it.s3-website-eu-west-1.amazonaws.com should be working now for any tablet.
Please confirm

**Comment by ajanes** [comment]
Works!
![IMG_7474](https://user-images.githubusercontent.com/10242827/59264574-afb3bb80-8c43-11e9-81da-f3b86459b540.jpg)

**Comment by bertolla** [comment]
Now also reachable under https://today.noi.bz.it
