### ISSUE TITLE
As NOI Communication I want the events to be categorized into the technology fields of the NOI

### ISSUE THREAD

**Issue by ohnewein** [idm-suedtirol/NOI-display#13]
The EventShort object needs a field, in which the editor can select the technology-field to assign it to.

A selection between:
- Alpine
- Automitive/Automation
- Digital
- Food
- Green

The content editor should be able to select 0, 1 or more related technology sectors for every event. Therefore in the Data Browser he should get a list containing checkboxes for the 5 technology sectors.

**Comment by RudiThoeni** [comment]
-Added Field to Json Output
-Added Field to Eventsnoi CMS

**Comment by RudiThoeni** [comment]
Jon Output is a string array

TechnologyFields: [
"Automotive/Automation"
]
