### ISSUE TITLE
As NOI communication or event organizer I want to be able to edit events even if they are provided by a data source

### ISSUE THREAD

**Issue by ohnewein** [idm-suedtirol/NOI-display#15]
Even for those event entries, which get synched from a data source (meeting management system), I want to be able to edit information. Add pictures (which seems to work) and other information, like "Organizer", "Web Page (URL)", ... 

Is it possible that some fields get overwritten on every sync from the data provider?

Is it possible to change this behavior?

**Comment by RudiThoeni** [comment]
at the moment you can edit the fields
-Images
-Description (DE,IT,EN)
-Web Page
-Video URL
-Technology Field
(these fields are not overwritten by a sync)

maybe it should be visualized on the edit dialog

**Comment by ohnewein** [comment]
I had a meeting with Alexia and Alida from the communication unit and Verena from Meeting Management. We found an agreement on how the workflows should be. And that all data has to be edited at the origin. That means:

data of events managed by Meeting Management will be edited by the Meeting Management team directly in the EURAC tool. NOI communication will inform the Meeting Management about errors in these data and can only edit the extended fields (like video, URL, ...) which do not get synched.

data of other events will be inserted and edited by the NOI communication unit directly in ODH. Also NOI partners (FH, UNIBZ, ...) will insert their events into ODH. NOI communication will be the main editor (redazione) of all data entries.

The marking of the fields, which get synched between EURAC tool and ODH would improve the UX of the editors.
