### ISSUE TITLE
Site under maitenance if there are no events planned

### ISSUE THREAD

**Issue by sseppi** [idm-suedtirol/NOI-display#19]
As you can see from the attached picture if there are no events planned the page today.noi.bz.it shows the message "Site under maintenance". this i quite confusing for the visitors.
I would suggest to change the message in "no events planned" or something similar
[
![Schermata da 2020-11-17 17-24-27](https://user-images.githubusercontent.com/7909989/99417659-741e2600-28fa-11eb-94f5-b3127580cbcc.png)
](url)

**Comment by ohnewein** [comment]
I assigned this bug to @bertolla , because being it a bug I think it should have priority.
