### ISSUE TITLE
As a NOI visual strategist (Lukas Nagler) I want to ridesign today.noi.bz.it in order to align it to the visual strategy of the NOI Techpark.

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/NOI-display#20]
Our Brand asked to review the graphics of today.noi.bz.it in both versions:
- screenwall of the Foyer
- Webpage.

The changes to be done are listed in the following presentation:
[link to presentation](https://noibz.sharepoint.com/:p:/s/UnitBrandCommunication/EZ6_Q5IDOfdHjF0-CMwuQx0BTlgkulgIFUiL4CkjtbtB_Q?e=EWyI3f)

**Comment by bertolla** [comment]
Everything ca be tested here
- https://today.noi.testingmachine.eu
- https://today.noi.testingmachine.eu/?location=foyer
- https://today.noi.testingmachine.eu/?location=D1

**Comment by sseppi** [comment]
According to the email of Lukas we can go live with the new version.
